---
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "0777"
- name: Install vector packages
  become: true
  ansible.builtin.yum:
    name:
      - vector-{{ vector_version }}-1.x86_64.rpm
    state: present
- name: Config template
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: vector.yml
    mode: "0777"
    validate: vector validate --no-environment --config-yaml %s