---
- name: Get vector distrib rpm
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    validate_certs: 0
    mode: "0777"
  when: ansible_pkg_mgr == "yum"

- name: Install vector rpm packages
  ansible.builtin.yum:
    name:
     - vector-{{ vector_version }}-1.x86_64.rpm
    allow_downgrade: yes
  when: ansible_pkg_mgr == "yum"
  notify: restart vector service

- name: Get vector distrib deb
  become: 1
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector.deb"
    validate_certs: 0
    mode: "0777"
  when: ansible_pkg_mgr == "apt"

- name: Install vector deb packages
  become: 1
  ansible.builtin.apt:
    deb: "/tmp/vector.deb"
  when: ansible_pkg_mgr == "apt"
  notify: restart vector service

- name: Get vector distrib rpm based for dnf packet manager
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    validate_certs: 0
    mode: "0777"
  when: ansible_pkg_mgr == "dnf"

- name: Install vector packages (dnf packet manager)
  ansible.builtin.dnf:
    name: vector-{{ vector_version }}-1.x86_64.rpm
    disable_gpg_check: 1
  when: ansible_pkg_mgr == "dnf"
  notify: restart vector service

- name: Generate vector config
  ansible.builtin.template: 
    src: vector.yaml.j2 
    dest: "{{ vector_config }}"
  notify: restart vector service
